ingredients = [
    "Acesulfame", "Achi", "Acorn", "Acorn Squash", "Afang", "African Pear", "African Star Apple", "Agar",
    "Agave Syrup", "Aidan Fruit", "Aji Amarillo", "Ajwain", "Ají Dulce", "Akamu Paste", "Akpi", "Alfalfa Sprouts",
    "Allspice", "Almond", "Almond Butter", "Almond Extract", "Almond Flour", "Almond Oil", "Almond Paste",
    "Amaranth", "Amchoor", "Anise", "Annatto", "Apple", "Apple Cider", "Applesauce", "Apricot", "Aquafaba",
    "Arrowroot", "Artichoke", "Arugula", "Asafoetida", "Ashanti Pepper", "Asian Pear", "Asparagus", "Aspartame",
    "Atama", "Avocado", "Azuki Bean", "Bacon", "Bagoong Alamang", "Baharat", "Baking Ammonia", "Baking Powder",
    "Baking Soda", "Bambara Bean", "Bamboo", "Banana", "Banana Blossom", "Baobab", "Barberry", "Barley",
    "Basil", "Bay Leaf", "Bean Sprout", "Beetroot", "Bell Pepper", "Berbere", "Bilberry", "Biltong", "Bitter Bean",
    "Bitter Melon", "Bitterleaf", "Black Bean", "Black Cardamom", "Blackberry", "Blackcurrant", "Blueberry",
    "Bok Choy", "Bonito Flakes", "Bouquet Garni", "Brassicas", "Bread", "Bread Crumbs", "Breadfruit",
    "Breading", "Breakfast Cereal", "Brie Cheese", "Broccoflower", "Broccoli", "Broccolini", "Broth and Stock",
    "Brown Rice Syrup", "Brown Sugar", "Brussels Sprout", "Buckwheat", "Buffaloberry", "Bulgur", "Butter",
    "Buttermilk", "Butternut Squash", "Cabbage", "Cake Flour", "Cake Mix", "Calabash Nutmeg", "Calabaza",
    "Calamansi", "Candlenut", "Cane Syrup", "Cantaloupe", "Caper", "Caraway", "Carbonated Water", "Cardamom",
    "Cargamanto", "Carp", "Carrot", "Cashew", "Cassava", "Cauliflower", "Cayenne Pepper", "Celery",
    "Celery Root", "Celery Seed", "Chanterelle", "Chard", "Chayote", "Cheddar Cheese", "Cheese", "Cheese Curds",
    "Cherimoya", "Cherry", "Chervil", "Chestnut", "Chia Seed", "Chickpea", "Chicory", "Chili Flakes",
    "Chili Paste", "Chili Sauce" "Chilis", "Chili Powder", "Chipotle Pepper", "Chive", "Chocolate", "Chokeberry",
    "Chorizo", "Cilantro", "Cinnamon", "Citric Acid", "Citrus", "Clarified Butter", "Clotted Cream", "Clove",
    "Cocoa Powder", "Coconut", "Coconut Oil", "Coffee", "Collard Greens", "Conch", "Condensed Milk", "Cooking Spray",
    "Coriander", "Corn", "Corn Flakes", "Corn Flour", "Corn Syrup", "Cornelian Cherry", "Cornmeal", "Cornstarch",
    "Cottage Cheese", "Cottonseed", "Court-bouillon", "Couscous", "Cowpea", "Crab Apple", "Cracker", "Cranberry",
    "Cream", "Cream Cheese", "Cream of Tartar", "Crouton", "Crumb Crust", "Crème de Menthe", "Crème Fraiche",
    "Cucumber", "Culantro", "Cumian", "Cumin", "Curry Leaf", "Curry Paste", "Curry Powder", "Custard Powder",
    "Dandelion", "Date", "Dehydrated Broth", "Demerara Sugar", "Digestive Biscuit", "Dill", "Douchi", "Dulce de Leche",
    "Dulse", "Durian", "Editan", "Egg", "Eggplant", "Egusi Seed", "Elephant Grass", "Emmental Cheese", "Erythritol",
    "Fava Bean", "Feijoa", "Fennel", "Fenugreek", "Feta Cheese", "Fiddlehead", "Fig", "Fireweed", "Flour",
    "Fluted Pumpkin", "Fonio", "Food Coloring", "Fructose", "Fruit Preserves", "Galangal", "Garlic", "Garlic Powder",
    "Gelatin", "Gem Squash", "Genger", "Giblets", "Ginger", "Ginger Garlic Paste", "Glass Noodle", "Glucose",
    "Gluten", "Gluten-Free Flour", "Gnocchi", "Gochujang", "Golden Syrup", "Gooseberry", "Gorgonzola Cheese", "Gourd",
    "Graham Cracker", "Graham Flour", "Grains", "Grains of Paradise", "Granulated Sugar", "Grape", "Grape Leaf",
    "Grapefruit", "Green Bean", "Green Onion", "Gruyère Cheese", "Guar Gum", "Guava", "Gula Jawa", "Habanero",
    "Hawthorn", "Hazelnut", "Hazelnut Oil", "Heart of Palm", "Herbes de Provence", "Ho Fun", "Hoisin Sauce",
    "Hominy", "Honey", "Hops", "Horned Melon", "Horseradish", "Hot Sauce", "Huacatay", "Huckleberry", "Hummus",
    "Hyssop", "Ice Cream", "Iceberg Lettuce", "Iru", "Isomalt", "Jackfruit", "Jaggery", "Jalapeño", "Jicama",
    "Juniper Berry", "Jute", "Kaffir Lime", "Kale", "Kamut", "Kangaroo", "Kansui", "Kaong", "Kasha", "Kefir",
    "Kelp", "Ketchup", "Kidney", "Kidney Bean", "Kimchi", "Kiwi", "Kohlrabi", "Konbu", "Kumquat",
    "Lagos Spinach", "Laver", "Leek", "Lemon", "Lemon Pepper", "Lemongrass", "Lentil", "Lettuce", "Licorice",
    "Lima Bean", "Lime", "Limewater", "Lingonberry", "Linguine", "Liquid Seasoning", "Liquid Smoke","Locust Bean",
    "Longan", "Lychee", "Macadamia", "Macaroni", "Mahogany Seed", "Maida", "Malabar Spinach", "Malt", "Mango",
    "Manioc Flour", "Maple Syrup", "Maraschino Cherry", "Margarine", "Marjoram", "Marmalade", "Marsala Wine",
    "Marshmallow", "Marugbo", "Marzipan", "Mascarpone Cheese", "Matcha", "Matzo Meal", "Mayonnaise", "Medlar",
    "Melon", "Mexican Mint", "Milk", "Millet", "Mint", "Mirin", "Miso", "Mixed Herbs", "Modified Food Starch",
    "Molasses", "Monterey Jack Cheese", "Moringa", "Mortadella", "Mozzarella Cheese", "MSG", "Muenster Cheese",
    "Mung Bean", "Mushroom", "Mustard", "Mustard Greens", "Mustard Oil", "Mustard Seed", "Nappa Cabbage",
    "Nata de Coco", "Neck Sweetbread", "Nectarine", "Nettle", "Nigella", "Nigerian Brown Bean", "Noodle",
    "Nopales", "Nori", "Nutella", "Nutmeg", "Nutritional Yeast", "Nuts and Seeds", "Oat Flour", "Oat Milk", "Oats",
    "Ogbono", "Ogiri", "Oha", "Oil Palm Fruit", "Okara", "Okoho", "Okpehe", "Okra", "Olive", "Olive Oil", "Onion",
    "Onion Powder", "Orange", "Orange Flower Water", "Orange Juice", "Oregano", "Orzo", "Palmyra Palm Fruit",
    "Pancetta", "Pandan", "Pandan Essence", "Papaya", "Paprika", "Parmesan Cheese", "Parsley", "Parsley Root",
    "Parsnip", "Passion Fruit", "Pasta", "Pastry Flour", "Pawpaw", "Pea", "Peach", "Peanut", "Peanut Butter",
    "Peanut Oil", "Pear", "Pecan", "Pecorino Cheese", "Pectin", "Pepino", "Pepper", "Pepperoncini",
    "Persimmon", "Pesto", "Phyllo Dough", "Pickle", "Pickling Salt", "Pigeon Pea", "Pimento", "Pine Nut",
    "Pineapple", "Pinto Bean", "Pistachio", "Plantain", "Plum", "Pomegranate", "Pomelo", "Poppy Seed",
    "Porcini Mushroom", "Potash", "Potato", "Potato Chip", "Potato Flour", "Potato Starch", "Powdered Sugar",
    "Prickly Pear", "Provolone Cheese", "Puff Pastry", "Pulses", "Pumpkin", "Pumpkin Pie Spice", "Pumpkin Purée",
    "Pumpkin Seed", "Quince", "Quinoa", "Radish", "Raisin", "Rambutan", "Ramen Noodle", "Ras el Hanout", "Raspberry",
    "Raw Sugar", "Reblochon Cheese", "Red Leicester Cheese", "Rhubarb", "Rice", "Rice Flour", "Rice Vinegar",
    "Rice Wafer", "Ricotta", "Roe", "Rolled Oats", "Romaine Lettuce", "Roselle", "Rosemary", "Rosewater",
    "Rutabaga", "Rye", "Saffron", "Sage", "Sago", "Salsa", "Salsify", "Salt", "Saltine Cracker", "Samphire", "Sapote",
    "Sauerkraut", "Savory", "Scent Leaf", "Seasoned Flour", "Seaweed", "Seitan", "Semolina", "Serrano Chili",
    "Sesame Leaf", "Sesame Oil", "Sesame Seed", "Sev", "Shallot", "Shatkora", "Shirataki", "Shiso", "Shortening",
    "Snap Pea", "Snow Pea", "Soba", "Soda Pop", "Somen", "Sorghum", "Sorrel", "Sour Cream", "Sour Mix",
    "Sourdough Starter", "Soybean", "Soy Sauce", "Spaghetti", "Spaghetti Squash", "Spelt", "Spinach", "Spirulina",
    "Sprinkles", "Squash", "Sriracha", "Star Anise", "Star Fruit", "Stinging Nettle", "Strawberry", "Sugar",
    "Sugarcane", "Sulfur Dioxide", "Sumac", "Sunchoke", "Sunflower Seeds", "Suya Spice", "Sweet Potato", "Syrup",
    "Szechuan Pepper", "Tahini", "Tallow", "Tamarillo", "Tamarind", "Tandoori Masala", "Tangerine", "Tapioca Pearls",
    "Tapioca Starch", "Taro Root", "Tarragon", "Tater Tots", "Tea", "Tea Leaves", "Teff", "Tempeh", "Thai Chili Paste",
    "Thyme", "Tiger Nut", "Tilapia", "Tofu", "Tomatillo", "Tomato", "Tomato Paste", "Tomato Sauce", "Tortilla",
    "Treacle", "Triticale", "Truffle", "Turbinado Sugar", "Turmeric", "Turnip", "Ube", "Udon", "Ugba", "Ugli Fruit",
    "Ujuju", "Uma Leaf", "Unsalted Butter", "Utazi", "Vanilla Extract", "Vegetable Oil", "Vegemite", "Vermicelli",
    "Vinegar", "Wakame", "Walnut", "Wasabi", "Water", "Water Chestnut", "Water Spinach", "Watercress", "Waterleaf",
    "Watermelon", "Wax Apple", "Wensleydale Cheese", "Wheat", "Wheat Flour", "Wheat Germ", "Whipped Cream",
    "Whipping Cream", "White Radish", "White Sugar", "Whole Wheat Flour", "Wild Rice", "Worcestershire Sauce",
    "Xanthan Gum", "Yam", "Yardlong Bean", "Yeast", "Yeast Extract", "Yogurt", "Yu Choy", "Zaatar", "Zest", "Zucchini"
]
ingredients = sorted(set(ingredients))
sql_statements = [f"insert into ingredient (name) values ('{ingredient}');" for ingredient in ingredients]
for statement in sql_statements:
   print(statement)
